trigger:
  branches:
    include:
      - main

pool:
  name: SD5346-practical-devops

variables:
  kubernetesServiceConnection: "azure-infrastructure-connection"
  namespace: "default"

stages:
  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - job: DeployJob
        displayName: Deploy Kubernetes Manifests
        steps:
          - checkout: self

          - task: Kubernetes@1
            displayName: Deploy MongoDB
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: $(kubernetesServiceConnection)
              namespace: $(namespace)
              command: apply
              useConfigurationFile: true
              configuration: kubernetes/mongodb.yaml

          - task: Kubernetes@1
            displayName: Deploy Backend
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: $(kubernetesServiceConnection)
              namespace: $(namespace)
              command: apply
              useConfigurationFile: true
              configuration: kubernetes/backend.yaml

          - task: Kubernetes@1
            displayName: Deploy Frontend
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: $(kubernetesServiceConnection)
              namespace: $(namespace)
              command: apply
              useConfigurationFile: true
              configuration: kubernetes/frontend.yaml

          - task: Kubernetes@1
            displayName: Deploy Ingress
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: $(kubernetesServiceConnection)
              namespace: $(namespace)
              command: apply
              useConfigurationFile: true
              configuration: kubernetes/ingress.yaml
